# Generated by Django 5.0.2 on 2024-02-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_car_remove_student_file_remove_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='speed',
            field=models.IntegerField(default=50),
        ),
    ]
