# Generated by Django 5.0.2 on 2024-02-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_subject_subjectmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
